# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: maxbo 

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 512
  timeout: 30
  stage: dev

  # These environment variables are made available to our functions
  # under process.env.
  environment:
    productsTableName: ${self:custom.productsTableName}
    customersTableName: ${self:custom.customersTableName}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      # Restrict our IAM role permissions to
      # the specific table for the stage
      Resource:
        - "Fn::GetAtt": [ productsTable, Arn ]
        - "Fn::GetAtt": [ customersTable, Arn ]

package:
  individually: true 
  exclude:
    - ./**

functions:
  mainPost:
    handler: src/webhook/mainPost.main
    events:
      - http:
          path: webhook
          method: post
    package:
      include: # Specify the directories and files which should be included in the deployment package for this specific function.
        - src/webhook/mainPost.js
        - src/messengerUtils/node_modules/**
        - src/jsUtils/jsUtils.js
        - src/messengerUtils/fbUtils.js
        - src/business/testing/foolingAround.js
        - src/business/constants.js
        - src/business/historyPath.js
        - src/business/responses.js
        - src/awsUtils/dynamoUtils.js
  mainGet:
    handler: src/webhook/mainGet.main
    events:
      - http:
          path: webhook
          method: get
    package:
      include: # Specify the directories and files which should be included in the deployment package for this specific function.
        - src/webhook/mainGet.js
        - src/jsUtils/jsUtils.js

  data2dynamo:
    handler: src/business/testing/data2dynamo.main
    package:
      include: # Specify the directories and files which should be included in the deployment package for this specific function.
        - src/business/testing/data2dynamo.js
        - src/business/testing/data.js
        - src/jsUtils/jsUtils.js

  getContactInfo:
    handler: src/api/getContactInfo.main
    events:
      - http:
          path: api/contactInfo/{id}
          method: get
          cors: true
    package:
      include:
        - src/api/getContactInfo.js
        - src/awsUtils/dynamoUtils.js
        - src/jsUtils/jsUtils.js

  saveContactInfo:
    handler: src/api/saveContactInfo.main
    events:
      - http:
          path: api/contactInfo/{id}
          method: post
          cors: true
    package:
      include:
        - src/api/saveContactInfo.js
        - src/awsUtils/dynamoUtils.js
        - src/jsUtils/jsUtils.js

  getProduct:
    handler: src/api/getProduct.main
    events:
      - http:
          path: api/product/{id}
          method: get
          cors: true
    package:
      include:
        - src/api/getProduct.js
        - src/awsUtils/dynamoUtils.js
        - src/jsUtils/jsUtils.js
    
  
resources:
  #DynamoDB
  - ${file(resources/dynamodb-tables.yml)}

custom:
  stage: ${opt:stage, self:provider.stage}
  productsTableName:  ${self:service}-${self:custom.stage}-abvinosProducts
  customersTableName:  ${self:service}-${self:custom.stage}-abvinosCustomers
  tableThroughputs:
    prod: 5
    default: 1
  tableThroughput: ${self:custom.tableThroughputs.${self:custom.stage}, self:custom.tableThroughputs.default}