module.exports.catalogoTest = [
    {
      "id":"1001",
      "tipo":"Tinto",
      "nombre":"Château Grandjean",
      "bodega":"Dulon",
      "cepas":"60% Merlot, 40% Cabernet Sauvignon",
      "anio":2016,
      "moneda":"S/",
      "precioMinorista":47,
      "precioMayorista":43,
      "umbralMayorista":6,
      "tipoData":"producto",
      "ubicacion":"VINOS DE BURDEOS - FRANCIA",
      "imageURL":"https://s3.amazonaws.com/maxbo-aws-image/chateau-grand-jean-min.jpg"
    },
    {
      "id":"1011",
      "tipo":"Tinto",
      "nombre":"Le Tertre du Sarpe Saint Emilion",
      "bodega":"Magnaudeix",
      "cepas":"100% Merlot",
      "anio":2011,
      "moneda":"S/",
      "precioMinorista":95,
      "precioMayorista":93,
      "umbralMayorista":6,
      "tipoData":"producto",
      "ubicacion":"VINOS DE BURDEOS - FRANCIA",
      "imageURL":"https://s3.amazonaws.com/maxbo-aws-image/copy_from_25235_to_1050440911_10504407_chateau_le_castelot_saint_emilion_grand_c.jpg"
    },
    {
      "id":"1012",
      "tipo":"Tinto",
      "nombre":"Pontificis",
      "bodega":"Badet Clément",
      "cepas":"Grenache, Syrah, Mourvedre",
      "anio":2014,
      "moneda":"S/",
      "precioMinorista":49,
      "precioMayorista":46,
      "umbralMayorista":6,
      "tipoData":"producto",
      "ubicacion":"VINOS DE BURDEOS - FRANCIA",
      "imageURL":"https://s3.amazonaws.com/maxbo-aws-image/Pontificis+Red+Wine-774x735.jpg"
    },
    {
      "id":"1002",
      "tipo":"Blanco",
      "nombre":"Château Grandjean",
      "bodega":"Dulon",
      "cepas":"70% Sémillon, 30% Sauvignon blanc",
      "anio":2017,
      "moneda":"S/",
      "precioMinorista":47,
      "precioMayorista":43,
      "umbralMayorista":6,
      "tipoData":"producto",
      "ubicacion":"VINOS DE BURDEOS - FRANCIA",
      "imageURL":"https://s3.amazonaws.com/maxbo-aws-image/chateau-grandjean-bordeaux-entre-deux-mers.jpg"
    },
    {
      "id":"1003",
      "tipo":"Blanco",
      "nombre":"Pontificis blanco",
      "bodega":"Badet Clément",
      "cepas":"Chardonnay, Viognier",
      "anio":2015,
      "moneda":"S/",
      "precioMinorista":49,
      "precioMayorista":46,
      "umbralMayorista":6,
      "tipoData":"producto",
      "ubicacion":"VINOS DE BURDEOS - FRANCIA",
      "imageURL":"https://s3.amazonaws.com/maxbo-aws-image/descarga.jpeg"
    },
    {
      "id":"1009",
      "tipo":"Blanco",
      "nombre":"Corazón Loco",
      "bodega":"Bodega Iniesta",
      "cepas":"60% Sauvignon blanc 40% Verdejo",
      "anio":2015,
      "moneda":"S/",
      "precioMinorista":45,
      "precioMayorista":42,
      "umbralMayorista":6,
      "tipoData":"producto",
      "ubicacion":"VINOS DE BURDEOS - FRANCIA",
      "imageURL":"https://s3.amazonaws.com/maxbo-aws-image/cl-tinto-prod.jpg"
    },
    {
      "id":"1004",
      "tipo":"Espumante Blanco",
      "nombre":"Clairette de Die Cuvée titus Rodano Sur",
      "bodega":"Jaillance",
      "cepas":"Muscat, Clairette à petits grains",
      "anio":-1,
      "moneda":"S/",
      "precioMinorista":65,
      "precioMayorista":59,
      "umbralMayorista":6,
      "tipoData":"producto",
      "ubicacion":"VINOS DE OTRAS ZONAS DE FRANCIA",
      "imageURL":"https://s3.amazonaws.com/maxbo-aws-image/image.jpeg"
    },
    {
      "id":"1005",
      "tipo":"Rosado",
      "nombre":"Corazón Loco",
      "bodega":"Bodega Iniesta",
      "cepas":"100% Bobal",
      "anio":2016,
      "moneda":"S/",
      "precioMinorista":45,
      "precioMayorista":42,
      "umbralMayorista":6,
      "tipoData":"producto",
      "ubicacion":"VINOS DE BURDEOS - FRANCIA",
      "imageURL":"https://s3.amazonaws.com/maxbo-aws-image/corazon-loco-rosado_1.jpg"
    }
  ]
